# Generated by Django 4.0.6 on 2022-08-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='last_login',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_login',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
