# Generated by Django 4.0.6 on 2022-08-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_last_login_patient_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='FirstName',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='LastName',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='FirstName',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='LastName',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
