# Generated by Django 4.0.6 on 2022-08-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_firstname_doctor_lastname_patient_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='FirstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='LastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='FirstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='LastName',
            field=models.CharField(max_length=100),
        ),
    ]
